sudo: false
language: php
php:
  - 5.5
#  - 5.6
#  - 7.0
#  - 7.1
#  - 7.2

before_script:
  # Want YAML.
  - pecl channel-update pecl.php.net
  - (CFLAGS="-O1 -g3 -fno-strict-aliasing"; pecl install yaml < /dev/null &)
  # Remove XDebug.
  - phpenv config-rm xdebug.ini
  # Git clone the Drupal 8.6.x repo, so that we can apply patches to it.
  - git clone --depth 1 --branch 8.6.x https://git.drupal.org/project/drupal.git
  # Apply patch. You only get one.
  - cd drupal
  - git apply --verbose ../patch/fixes.patch
  - cd ..
  # Copy the tests out of core. Copy only the component tests or
  # PHPUnit will complain that it can't find classes during discovery.
  - mkdir -p workspace/core/tests/Drupal/Tests
  - cp -R drupal/core/tests/Drupal/Tests/Component ./workspace/core/tests/Drupal/Tests/
  - test -f workspace/core/tests/Drupal/Tests/Component/DrupalComponentTest.php
  - composer install --no-progress --no-suggest

script:
  # Run our tester script. It will always die on fail or error.
  - php tester.php
